### ISSUE TITLE
example/CMakeLists.txt file missing include(../generic-gcc-avr.cmake)

### ISSUE THREAD

**Issue by kingadami** [mkleemann/cmake-avr#6]
The CMakeLists.txt file is missing the include(../generic-gcc-avr.cmake) line after the END TOOLCHAIN SETUP AREA line in the example directory.

**Comment by mkleemann** [comment]
This is intentional and describes a different approach than the one in the C++ example. Please see the README for both examples. You need to call teh file in the command line here. In your own project environment, of course, you can use the include statement rather than the less convenient one in the cmake command line.
